const songs = [
    {title:'Giá Như',src: 'songs/SOOBIN_-_gia_nh_Official_MV_[_YouConvert.net_].mp3', name: 'Giá Như', artist: 'Soobin Hoàng Sơn', cover: 'img/soobin_album.png' },
    {title:'HEYY',src: 'songs/SOOBIN_-_HEYYY_Official_MV_[_YouConvert.net_].mp3', name: 'HEYY', artist: 'Soobin Hoàng Sơn', cover: 'img/soobin_album.png' },
    {title:'Sẽ Quên Em Nhanh Thôi',src: 'songs/SOOBIN_-_S_Quen_Em_Nhanh_Thoi_BT_NO_LEN_Album_(Official_Visualizer)_[_YouConvert.net_].mp3', name: 'Sẽ Quên Em Nhanh Thôi', artist: 'Soobin Hoàng Sơn', cover: 'img/soobin_album.png' },
    {title:'Sunset In The City',src: 'songs/SOOBIN_-_Sunset_In_The_City_(Deluxe_Version)_BT_NO_LEN_Album_(Official_Visualizer)_[_YouConvert.net_].mp3', name: 'Sunset In The City', artist: 'Soobin Hoàng Sơn', cover: 'img/soobin_album.png' },
    {title:'Lu Mờ',src: 'songs/SOOBIN,_Kris_V_-_Lu_M_B_T_NO_LEN_Album_(Official_Visualizer)_[_YouConvert.net_].mp3', name: 'Lu Mờ', artist: 'Soobin Hoàng Sơn, Kris V', cover: 'img/soobin_album.png' },
    {title:'Ai Mà Biết Được',src: 'songs/SOOBIN,_tlinh_-_Ai_Ma_Bi_t_c_(ft._Touliver)_B_T_NO_LEN_Album_(Official_MV)_[_YouConvert.net_].mp3', name: 'Ai Mà Biết Được', artist: 'Soobin Hoàng Sơn, tlinh ( ft.Touliver ) ', cover: 'img/soobin_album.png' },
    {title:'Tràn Bộ Nhớ', src: 'songs/Tran_B_Nh_-_Dng_Domic_Lyrics_Video_[_YouConvert.net_].mp3', name: 'Tràn Bộ Nhớ', artist: 'Dương Domic', cover: 'img/tranbonho.png' },
    {title:'Catch Me If You Can',src: 'songs/CATCH ME IF YOU CAN.mp3', name: 'Catch Me If You Can', artist: 'NEGAV, Quang Hùng MasterD, Công Dương, Nicky', cover: 'img/sayhi.jpg' },
    {title:'Hào Quang',src: 'songs/Hào Quang.mp3', name: 'Hào Quang', artist: 'Pháp Kiều x Rhyder x Dương Domic', cover: 'img/sayhi.jpg' },
    {title:"I'M THINKING ABOUT YO", src: "songs/I'M THINKING ABOUT YOU.mp3", name: "I'M THINKING ABOUT YOU", artist: 'Hùng Huỳnh, Rhyder, Đức Phúc, WEAN, tlinh', cover: 'img/sayhi.jpg' },
    {title:'Kim Phút Kim Giớ', src: 'songs/Kim Phúc Kim Giờ.mp3', name: 'Kim Phúc Kim Giờ', artist: 'HIEUTHUHAI, Pháp Kiều, NEGAV, Issac, HURRYKNG', cover: 'img/sayhi.jpg' },
    {title:'Làn Ưu Tiên', src: 'songs/Làn Ưu Tiên.mp3', name: 'Làn Ưu Tiên', artist: 'Mopius', cover: 'img/sayhi.jpg' },
    {title:'Mashup Mất Kết Nối x Nỗi Đau Đính Kèm', src: 'songs/Mashup Mat Ket Noi x Noi Dau Dinh Kem.mp3', name: 'Mashup Mất Kết Nối x Nỗi Đau Đính Kèm', artist: 'Dương Domic, Anh Tú Atus, Rhyder', cover: 'img/sayhi.jpg' },
    {title:'Ngáo Ngơ', src: 'songs/Ngáo Ngơ.mp3', name: 'Ngáo Ngơ', artist: 'HIEUTHUHAI, ERIK, JSON, Anh Tú Atus, Orange', cover: 'img/sayhi.jpg' },
    {title:'Quay Đi Quay Lại', src: 'songs/QUAY ĐI QUAY LẠI.mp3', name: 'Quay Đi Quay Lại', artist: 'HIEUTHUHAI', cover: 'img/sayhi.jpg' },
    {title:'Regret', src: 'songs/REGRET.mp3', name: 'REGRET', artist: 'Quang Trung, Ali Hoàng Dương, Pháp Kiều, Quân AP, Lâm Bảo Ngọc', cover: 'img/sayhi.jpg' },
    {title:'Walk', src: 'songs/WALK.mp3', name: 'WALK', artist: 'HIEUTHUHAI, Pháp Kiều, NEGAV, Issac, HURRYKNG', cover: 'img/sayhi.jpg' },
    { title:'Việt Nam Tôi Đó',src: 'songs/VIỆT NAM TÔI ĐÓ  SOOBIN x Vũ Cát Tường x Lil Wuyn  WCAs 2024.mp3', name: 'Việt Nam Tôi Đó', artist: 'SOOBIN x Vũ Cát Tường x Lil Wuyn', cover: 'img/OIP.jpg' },
    {title:'A Ă Â', src: 'songs/A Ă Â  WEAN x Anh Phan x Queen B  Album WCAs 2024.mp3', name: 'A Ă Â', artist: 'WEAN x Anh Phan x Queen B', cover: 'img/wc2024.png' },
    {title:'Bôn Ba (Nước Ngoài)', src: 'songs/BÔN BA (NƯỚC NGOÀI)  Phan Mạnh Quỳnh x Tăng Duy Tân x DuongK  WCAs 2023.mp3', name: 'BÔN BA (NƯỚC NGOÀI)', artist: 'Phan Mạnh Quỳnh x Tăng Duy Tân x DuongK', cover: 'img/wechoice2023.jpg' },
    {title:'Bắc Bling', src: 'songs/Bắc Bling.mp3', name: 'Bắc Bling', artist: 'HOÀ MINZY ft NS XUÂN HINH x MASEW x TUẤN CRY', cover: 'img/bacbling.png' },
    {title:'Chương mới', src: 'songs/Chương Mới.mp3', name: 'Chương mới', artist: 'NGUYỄN THÚC THUỲ TIÊN x WEAN ', cover: 'img/chuongmoi.png' },
    {title:'Chuyến đi của Thanh Xuân', src:"songs/Chuyến đi của Thanh Xuân - KHẮC HƯNG x SUNI HẠ LINH x BITI'S HUNTER.mp3", name: 'Chuyến đi của Thanh Xuân', artist: 'KHẮC HƯNG x SUNI HẠ LINH', cover: 'img/Chuyendithanhxuan.png' },
    {title:'Đi Giữa Trời Rực Rỡ', src: 'songs/Đi Giữa Trời Rực Rỡ - Ngô Lan Hương.mp3', name: 'Đi Giữa Trời Rực Rỡ', artist: 'Ngô Lan Hương ', cover: 'img/DGTRR.png' },
     {title:'Em Không Hiểu', src: 'songs/Em Không Hiểu - Changg.mp3', name: 'Em Không Hiểu', artist: 'Changg ', cover: 'img/Emkhonghieu.png' },
     {title:'Lời Đường Mật', src: 'songs/Lời Đường Mật - HIEUTHUHAI, Lyly.mp3', name: 'Lời Đường Mật', artist: 'HIEUTHUHAI, Lyly ', cover: 'img/LMT.png' },
     {title:'Sài Gòn Hôm Nay Mưa', src: 'songs/Sài Gòn Hôm Nay Mưa - Json, Hoàng Duyên.mp3', name: 'Sài Gòn Hôm Nay Mưa', artist: 'Json, Hoàng Duyên ', cover: 'img/sAIGONHOMNAYMUA.png' },
     {title:'Ai Cũng Phải Bắt Đầu Từ Đâu Đó', src: 'songs/AiCungPhaiBatDauTuDauDo-HIEUTHUHAI-11966356.mp3', name: 'Ai Cũng Phải Bắt Đầu Từ Đâu Đó', artist: 'HIEUTHUHAI', cover: 'img/ht2_album.png'  },

     {title:'1800', src: 'songs/HIEUTHUHAI,_HURRYKNG,_MANBO_1-800-LOVE_Official_Video_[_YouConvert.net_].mp3', name: '1800', artist: 'HIEUTHUHAI, HURRYKNG, MANBO ', cover: 'img/1800.png' },
    { 
        title:'Cái Đẹp',
        src: 'songs/CÁI ĐẸP   tlinh x Pháo x Pháp Kiều  Album WCAs 2024.mp3', 
        name: 'CÁI ĐẸP', 
        artist: 'tlinh x Pháo x Pháp Kiều', 
        cover: 'img/wechoice20244.png' 
    },
    { title:'Cầu Vồng Lấp Lánh',
        src: 'songs/CẦU VỒNG LẤP LÁNH  Văn Mai Hương x Myra Trần x Hứa Kim Tuyền  WCAs 2023.mp3', 
        name: 'CẦU VỒNG LẤP LÁNH', 
        artist: 'Văn Mai Hương x Myra Trần x Hứa Kim Tuyền', 
        cover: 'img/wechoice2023.jpg' 
    },
    { title:'Dám Rực Rỡ',
        src: 'songs/Dám Rực Rỡ  GREY D x HIEUTHUHAI x Wren Evans x Obito  Prod. by 2pillz & Kai Đinh  WCAs 2023.mp3', 
        name: 'Dám Rực Rỡ', 
        artist: 'GREY D x HIEUTHUHAI x Wren Evans x Obito', 
        cover: 'img/wechoice2023.jpg'  
    },
    { title:'Đến Là Đón',
        src: 'songs/ĐẾN LÀ ĐÓN  Tage, RHYDER, LOPE PHAM  Album WCAs 2024.mp3', 
        name: 'ĐẾN LÀ ĐÓN', 
        artist: 'Tage, RHYDER, LOPE PHAM', 
        cover: 'img/denladon.png' 
    },
    { title:'Giàu Nhất Khu Phù Hoa',
        src: 'songs/GIÀU NHẤT KHU PHÙ HOA  JustaTee, Wxrdie, Gill, Dangrangto, Robber  Album WCAs 2024.mp3', 
        name: 'GIÀU NHẤT KHU PHÙ HOA', 
        artist: 'JustaTee, Wxrdie, Gill, Dangrangto, Robber', 
        cover: 'img/wechoice2024.png' 
    },
    { title:'Miền Đất Kỳ Diệu',
        src: 'songs/MIỀN ĐẤT KỲ DIỆU  Hoàng Dũng, Kimmese, 52Hz, JustaTee  Album WCAs 2024.mp3', 
        name: 'MIỀN ĐẤT KỲ DIỆU', 
        artist: 'Hoàng Dũng, Kimmese, 52Hz, JustaTee', 
        cover: 'img/miendatkydieu.png',


    },
    { title:'Mưa Nào Mà Hông Tạnh',
        src: 'songs/Mưa Nào Mà Hông Tạnh  AMEE x Phúc Du x WOKEUP x Trid Minh  WCAs 2023.mp3', 
        name: 'Mưa Nào Mà Hông Tạnh', 
        artist: 'AMEE x Phúc Du x WOKEUP x Trid Minh', 
        cover: 'img/muanaomahongtanh.png' 
    },
    { title:'Phong Long',
        src: 'songs/PHONG LONG  Low G x Obito x WOKEUP  WCAs 2023.mp3', 
        name: 'PHONG LONG', 
        artist: 'Low G x Obito x WOKEUP', 
        cover: 'img/wechoice2023.jpg' 
    },
    { title:'Tóc Ngắn Ngắn',
        src: 'songs/TÓC NGẮN NGẮN  Diva Mỹ Linh x Liu Grace x Pháp Kiều x DuongK  WCAs 2023.mp3', 
        name: 'TÓC NGẮN NGẮN', 
        artist: 'Diva Mỹ Linh x Liu Grace x Pháp Kiều x DuongK', 
        cover: 'img/wechoice2023.jpg' 
    },
];
module.exports = songs;